[package]
name = "octovalve-console"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
tauri-build = "1.5.4"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.5.4", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
