[package]
name = "octovalve-console"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
futures-util = "0.3"
humantime = "2.1"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.5.4", features = ["window-start-dragging", "process-command-api"] }
toml = "0.8"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "time"] }
tokio-tungstenite = "0.23"
urlencoding = "2.1"
uuid = { version = "1.8", features = ["v4"] }

[features]
custom-protocol = ["tauri/custom-protocol"]

[workspace]
