[package]
name = "octovalve-console"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
futures-util = "0.3"
libc = "0.2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.5.4", features = ["process-command-api"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "time"] }
tokio-tungstenite = "0.23"

[features]
custom-protocol = ["tauri/custom-protocol"]

[workspace]
