[defaults]
local_bind = "127.0.0.1"
# ssh_args = ["-o", "IdentitiesOnly=yes"]
# ssh_password = "your-password"

[[targets]]
name = "example-target"
ssh = "devops@192.168.2.162"
# ssh_args = ["-i", "~/.ssh/id_ed25519"]
# ssh_password = "your-password"

[[targets.forwards]]
purpose = "data"
local_port = 19311
remote_addr = "127.0.0.1:19307"

[[targets.forwards]]
purpose = "control"
local_port = 19411
remote_addr = "127.0.0.1:19308"
